export const listData = [
  {
    id: 1,
    title: "A Cozy Apartment in the Heart of Kampala",
    img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/93/6f/a3/speke-apartments.jpg?w=900&h=-1&s=1",
    bedRoom: 2,
    bathRoom: 1,
    price: 600,
    address: "123 Kampala Road, Kampala",
    latitude: 0.3156,
    longitude: 32.5656,
  },
  {
    id: 2,
    title: "Luxury Condo with a View",
    img: "https://kampalasuburbs.com/wp-content/uploads/2020/09/DSCF2243-1-scaled-2048x1366.jpg",
    bedRoom: 3,
    bathRoom: 2,
    price: 1200,
    address: "456 Jinja Road, Kampala",
    latitude: 0.3188,
    longitude: 32.5902,
  },
  {
    id: 3,
    title: "Affordable Apartment in the Suburbs",
    img: "https://media-cdn.tripadvisor.com/media/vr-splice-j/07/0a/b6/1c.jpg",
    bedRoom: 1,
    bathRoom: 1,
    price: 300,
    address: "789 Ggaba Road, Kampala",
    latitude: 0.2871,
    longitude: 32.6371,
  },
  {
    id: 4,
    title: "Spacious House with Garden",
    img: "https://kampalasuburbs.com/wp-content/uploads/2020/09/DSCF2243-1-scaled-2048x1366.jpg",
    bedRoom: 4,
    bathRoom: 3,
    price: 1500,
    address: "12 Kololo Hill Drive, Kampala",
    latitude: 0.334,
    longitude: 32.6056,
  },
  {
    id: 5,
    title: "Modern Studio in Downtown Kampala",
    img: "https://tse2.mm.bing.net/th?id=OIP.y4BZeT5HlU6u92JclYWMcQHaFj&pid=Api&P=0&h=180.jpg",
    bedRoom: 1,
    bathRoom: 1,
    price: 400,
    address: "34 Bugolobi Road, Kampala",
    latitude: 0.3132,
    longitude: 32.6106,
  },
  {
    id: 6,
    title: "Charming Apartment Near Lake Victoria",
    img: "https://tse1.mm.bing.net/th?id=OIP.OohBXQmp00xqNaZh7sWk9gHaE8&pid=Api&P=0&h=180.jpg",
    bedRoom: 2,
    bathRoom: 2,
    price: 800,
    address: "23 Munyonyo Road, Kampala",
    latitude: 0.2637,
    longitude: 32.6082,
  },
  {
    id: 7,
    title: "Elegant Penthouse with City Views",
    img: "https://tse2.mm.bing.net/th?id=OIP.egXcXGFaMLC6A9yAtTv-_QHaFj&pid=Api&P=0&h=180.jpg",
    bedRoom: 4,
    bathRoom: 3,
    price: 2000,
    address: "78 Nakasero Hill, Kampala",
    latitude: 0.3265,
    longitude: 32.5822,
  },
  {
    id: 8,
    title: "Budget-Friendly Room in a Shared House",
    img: "https://tse2.mm.bing.net/th?id=OIP.PxeVJRYb-IOaRYnx0bu9TAHaFj&pid=Api&P=0&h=180.jpg",
    bedRoom: 1,
    bathRoom: 1,
    price: 200,
    address: "56 Nakawa Street, Kampala",
    latitude: 0.3293,
    longitude: 32.6304,
  },
  {
    id: 9,
    title: "Family Home in a Quiet Neighborhood",
    img: "https://tse3.mm.bing.net/th?id=OIP.mGs4Bg_JQ10tgPOuJ7JCDwHaFj&pid=Api&P=0&h=180.jpg",
    bedRoom: 3,
    bathRoom: 2,
    price: 900,
    address: "14 Ntinda Road, Kampala",
    latitude: 0.3454,
    longitude: 32.6148,
  },
  {
    id: 10,
    title: "Contemporary Loft in Central Kampala",
    img: "https://tse1.mm.bing.net/th?id=OIP.sJw4SBK-45SJuW9ZoVLZiAHaFj&pid=Api&P=0&h=180.jpg",
    bedRoom: 2,
    bathRoom: 1,
    price: 700,
    address: "90 Kira Road, Kampala",
    latitude: 0.336,
    longitude: 32.5885,
  },
];

export const singlePostData = {
  id: 1,
  title: "Beautiful Apartment",
  price: 600,
  images: [
    "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/93/6f/a3/speke-apartments.jpg?w=900&h=-1&s=1",
    "https://tse1.mm.bing.net/th?id=OIP.sJw4SBK-45SJuW9ZoVLZiAHaFj&pid=Api&P=0&h=180.jpg",
    "https://tse1.mm.bing.net/th?id=OIP.OohBXQmp00xqNaZh7sWk9gHaE8&pid=Api&P=0&h=180.jpg",
    "https://tse3.mm.bing.net/th?id=OIP.mGs4Bg_JQ10tgPOuJ7JCDwHaFj&pid=Api&P=0&h=180.jpg",
  ],
  bedRoom: 2,
  bathroom: 1,
  size: 861,
  latitude: 0.3156,
  longitude: 32.5656,
  city: "London",
  address: "123 Kampala Road, Kampala",
  school: "250m away",
  mainRoad: "100m away",
  restaurant: "50m away",
  description:
    "Future alike hill pull picture Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique sint temporibus voluptate, harum sequi recusandae aspernatur veritatis architecto quo quos unde nam aperiam quibusdam sit corporis eos fuga quasi placeat.swim dndjdhfn loremmffjjfnndncjddjdncdjdjrjnnfjdkdkrndmddkrkjr mfkdmdsl rndckm  nhcbhjdng juvghmjvghuhgvd",
};

export const userData = {
  id: 1,
  name: "Jumae Doe",
  img: "https://tse3.mm.bing.net/th?id=OIP.mGs4Bg_JQ10tgPOuJ7JCDwHaFj&pid=Api&P=0&h=180.jpg",
};
